name: BlackDuck Scan Workflow Spring Upgrade

on:
  push:
    branches:
      - teams/DCT-46433-Upgrade-spring-boot
  schedule:
    - cron:  '0 0 * * SUN'
  workflow_dispatch:

jobs:
  build:
    if: contains(github.ref, 'teams/DCT-46433-Upgrade-spring-boot') == true
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 'PREP - GitHub context'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: 'SETUP - Checkout Branch Code'
        uses: actions/checkout@v2

      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - name: 'SETUP - JAVA JDK 17'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu"

      - name: 'GRANT PERMISSION - Grant execute permission for gradlew'
        run: chmod +x gradlew

      - name: 'SETUP - Cache Gradle packages'
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: 'SETUP - gradle.properties'
        run: |
          echo "artifactoryContextUrl=${{ secrets.LCT_ARTIFACTORY_CONTEXT_URL }}" >> gradle.properties
          echo "artifactoryUsername=${{ secrets.LCT_ARTIFACTORY_USERNAME }}" >> gradle.properties
          echo "artifactoryPassword=${{ secrets.LCT_ARTIFACTORY_PASSWORD }}" >> gradle.properties
      - name: "BUILD - Build with Gradle"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --refresh-dependencies build -x test
      - id: temp_gh_access_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.PLAT_LCT_GHAPP_ID }}
          private_key: ${{ secrets.PLAT_LCT_GHAPP_PRIV_KEY }}

      - name: Set scan mode
        id: scan-mode
        shell: bash
        run: |
          if [[ "${GITHUB_REF_NAME}" == "teams/DCT-46433-Upgrade-spring-boot" ]]; then
              echo "data=INTELLIGENT" >> $GITHUB_OUTPUT
          else
              echo "data=RAPID" >> $GITHUB_OUTPUT
          fi
      - name: 'Blackduck scan'
        id: bd-scan
        uses: synopsys-sig/detect-action@v0.3.4
        env:
          DETECT_PROJECT_NAME: plat-lct-chat-service
          DETECT_PROJECT_VERSION_NAME: Upgrade-Spring-boot-1
          DETECT_REQUIRED_DETECTOR_TYPES: GRADLE
          DETECT_TOOLS_EXCLUDED: SIGNATURE_SCAN
          DETECT_PROJECT_USER_GROUPS: plat-lct-users,plat-lct-admins
          DETECT_PROJECT_CODELOCATION_UNMAP: true
          DETECT_WAIT_FOR_RESULTS: true
          DETECT_RISK_REPORT_PDF: true
          DETECT_BLACKDUCK_SIGNATURE_SCANNER_UPLOAD_SOURCE: false
          DETECT_BLACKDUCK_SIGNATURE_SCANNER_EXCLUSION_PATTERN_SEARCH_DEPTH: 0
          DETECT_REPORT_TIMEOUT: 600
          DETECT_PROJECT_TAGS: lct
        with:
          detect-version: 8.1.1
          scan-mode: ${{ steps.scan-mode.outputs.data }}
          github-token: ${{ steps.temp_gh_access_token.outputs.token }}
          blackduck-url: ${{ secrets.DS_BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.PLAT_LCT_BLACKDUCK_TOKEN }}
          fail-on-all-policy-severities: false

      # - name: Notify Teams Channel
      #   uses: aliencube/microsoft-teams-actions@v0.8.0
      #   with:
      #     webhook_uri: ${{ secrets.LCT_BLACKDUCK_MS_TEAMS_WEBHOOK }}
      #     title: "${{ env.REPOSITORY_NAME }} : SUCCESSFUL"
      #     summary: "${{ env.REPOSITORY_NAME }} : SUCCESSFUL"