
name: 'Export repository secrets to BY PD'
on:
  workflow_dispatch:
jobs:
  export_secrets:
    name: Export Secrets
    runs-on: [self-hosted, ds-github]
    steps:      
      - name: Checkout migration repo
        uses: actions/checkout@v2
        with:
          repository: JDA-Product-Development/ds-github-migrate-secrets
          ref: main
          ssh-key: ${{ secrets.DS_MIGRATION_CHECKOUT_SSH_KEY }}
          persist-credentials: false
          path: ./actions
         
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.DS_MIGRATION_GHAPP_ID }}
          private_key: ${{ secrets.DS_MIGRATION_GHAPP_SSH_KEY }}
          repository: BY-Product-Development/ds-github-migration-secrets

##### Change this section with the information of your repo and secret.
#     Note that you will need to repeat this code block per each repository  
#     secret you want to migrate. You must include repository secrets only. 
#     No organizational secret needs to be added

      - name: Export AZURE_CREDENTIALS_JDA_PD_DEV_TEST # Set step name as desired
        id: AZURE_CREDENTIALS_JDA_PD_DEV_TEST # Recommended: Adding the id with the secret name.
        uses: ./actions/migration
        with:
          repository_name: 'plat-lct-chat-service' #Change per your repository name
          secret_name: 'AZURE_CREDENTIALS_JDA_PD_DEV_TEST' #Add your secret name
          secret_value: "${{ secrets.AZURE_CREDENTIALS_JDA_PD_DEV_TEST }}" #Provide the secret value
          token: "${{ steps.generate_token.outputs.token }}"
          encryption_password: "${{ secrets.DS_MIGRATION_ENCRYPTION_KEY }}"
      - name: Export CODACY_PROJECT_TOKEN # Set step name as desired
        id: AZURE_CREDENTIALS_JDADELIVERS_DEV # Recommended: Adding the id with the secret name.
        uses: ./actions/migration
        with:
          repository_name: 'plat-lct-bff' #Change per your repository name
          secret_name: 'AZURE_CREDENTIALS_JDADELIVERS_DEV' #Add your secret name
          secret_value: "${{ secrets.AZURE_CREDENTIALS_JDADELIVERS_DEV }}" #Provide the secret value
          token: "${{ steps.generate_token.outputs.token }}"
          encryption_password: "${{ secrets.DS_MIGRATION_ENCRYPTION_KEY }}"
      - name: Export YOGESH_PAT # Set step name as desired
        id: YOGESH_PAT # Recommended: Adding the id with the secret name.
        uses: ./actions/migration
        with:
          repository_name: 'plat-lct-bff' #Change per your repository name
          secret_name: 'YOGESH_PAT' #Add your secret name
          secret_value: "${{ secrets.YOGESH_PAT }}" #Provide the secret value
          token: "${{ steps.generate_token.outputs.token }}"
          encryption_password: "${{ secrets.DS_MIGRATION_ENCRYPTION_KEY }}"
