name: Tag a branch | latest commit only

# This is a workflow to add release related tags to a commit
# Use this to add tags like "2022.1.0-rc.123" to the latest release branch
# Assumptions : This will tag the latest commit of the branch name entered

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: Enter the tag string
        required: true

jobs:
  tag:

    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
          private_key: ${{ secrets.PLAT_LCT_GHAPP_PRIV_KEY }}
          app_id: ${{ secrets.PLAT_LCT_GHAPP_ID }}
    - name: checkout
      uses: actions/checkout@v2
    - name: package-version-to-git-tag
      uses: pkgdeps/git-tag-action@v2
      with:
        github_token: ${{ steps.generate_token.outputs.token }}
        github_repo: ${{ github.repository }}
        git_commit_sha: ${{ github.sha }}
        version: ${{github.event.inputs.tagName}}
    - name: Echo details
      run : echo Tagged latest commit of ${GITHUB_REF##*/} with tag ${{github.event.inputs.tagName}}
